### ISSUE TITLE
Ignore secrets via CLI

### ISSUE THREAD

**Issue by sl4vr** [ClarkSource/k8t#57]
It would be handy to provide to cli some argument which will override secrets config.
In particular: I want to generate and review production manifests, but don't have access to its ssm. So I would like to provide some argument to `k8t gen` and generate manifests without access to secret provider.
I think we could implement some kind of stub secret provider, which would replace all secrets with some predefined or user-selected word. It would be helpful to make possible to distinguish values fetched from secrets from other values (from values.yaml, or even embedded in templates) after k8s manifests generated.

**Comment by AFriemann** [comment]
resolved by the `--secret-provider` flag, use

```
$ k8t gen --secret-provider random
```

to override it
